services:
  uvr:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./inputs:/uvr/inputs
      - ./outputs:/uvr/outputs
      - ./models:/uvr/models
    environment:
      - DISPLAY=unix:0.0
      - GDK_SCALE
      - GDK_DPI_SCALE
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              device_ids: [ '0' ]
#              capabilities: [ gpu ]
